const SENDED_CONFIRMATION_FORM = 'SENDED_CONFIRMATION_FORM';
const RECEIVED_CONFIRMATION_FORM = 'RECEIVED_CONFIRMATION_FORM';
const CHANGE_CONFIRMATION_FORM_ITEM = 'CHANGE_CONFIRMATION_FORM_ITEM';
const REMOVE_CONFIRMATION_FORM_ITEM = 'REMOVE_CONFIRMATION_FORM_ITEM';
const ADD_CONFIRMATION_FORM_ITEM = 'ADD_CONFIRMATION_FORM_ITEM';
const CHANGE_CONFIRMATION_FORM = 'CHANGE_CONFIRMATION_FORM';
const VALIDATE_CONFIRMATION_FORM = 'VALIDATE_CONFIRMATION_FORM';
const CHANGE_COUNTDOWN = 'CHANGE_COUNTDOWN';

export default {
  SENDED_CONFIRMATION_FORM,
  RECEIVED_CONFIRMATION_FORM,
  CHANGE_CONFIRMATION_FORM_ITEM,
  REMOVE_CONFIRMATION_FORM_ITEM,
  ADD_CONFIRMATION_FORM_ITEM,
  CHANGE_CONFIRMATION_FORM,
  VALIDATE_CONFIRMATION_FORM,
  CHANGE_COUNTDOWN,
};
